name: security check
on:
  push:
    branches:
      - main
    paths: './github/workflows/**'

permissions:
  contents: read

jobs:
  scan-on-all-worlflows:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: Run Checkov Security Scan on workflows files
      uses: bridgecrewio/checkov-action@master
      with:
        directory:  .github/workflows
        output_format: cli
        soft_fail: true
        quiet: true

  
